[package]
name = "qr_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
image = "0.25.5"
imagepipe = "0.5.0"
kdam = "0.6.2"
qrcode = "0.14.1"
rqrr = "0.9.0"
